# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sllti' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sllti

pod 'Alamofire', '~> 4.5'
pod 'Moya', '~> 10.0'
pod 'RealmSwift'
pod 'ObjectMapper'
pod 'DropDown'
pod 'IQKeyboardManagerSwift'
pod 'SVProgressHUD'
pod 'Toast-Swift', '~> 3.0.1'
pod 'DateToolsSwift'
pod 'NVActivityIndicatorView'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Tabman', '~> 1.0'
pod 'GooglePlacePicker'
pod 'Toast-Swift', '~> 3.0.1'
end
